; Motiva installer. Build with installer\build-installer.ps1 (Release build ->
; `deploy` target -> clean staging -> this script -> release\MotivaSetup.exe).
;
; Visual design: every visible control is Motiva-drawn. Inno Setup's native
; buttons / checkboxes / progress bar cannot be restyled, so they are moved
; off-screen (their logic is kept) and replaced by bitmap-drawn controls
; (installer\assets\ui\*.bmp, generated by installer\make-art.ps1) that
; forward clicks to the native buttons, so navigation, validation and the
; cancel confirmation are still Inno's own. Progress and step status are
; driven by Inno's real install events - nothing is simulated.
#define AppName "Motiva"
#define AppVersion "1.0.0"
#define AppPublisher "Robin Gupta Studios"
#define StagingDir "..\release\staging"

[Setup]
AppId={{6D0F3B52-7A1E-4C1B-9B0B-4D0E5A6F2C91}
AppName={#AppName}
AppVersion={#AppVersion}
AppVerName={#AppName} {#AppVersion}
AppPublisher={#AppPublisher}
AppCopyright=Copyright © Robin Gupta
VersionInfoVersion=1.0.0.0
VersionInfoCompany={#AppPublisher}
VersionInfoCopyright=Copyright © Robin Gupta
VersionInfoProductName={#AppName}
VersionInfoDescription={#AppName} Setup
; Per-user install: Motiva only writes to HKCU / per-user Start Menu, so no
; administrator rights (and no "install for all users?" prompt) are needed.
PrivilegesRequired=lowest
DefaultDirName={autopf}\{#AppName}
DisableProgramGroupPage=yes
DisableWelcomePage=no
DisableDirPage=yes
DisableReadyPage=yes
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
OutputDir=..\release
OutputBaseFilename=MotivaSetup
SetupIconFile=assets\motiva.ico
UninstallDisplayIcon={app}\resources\bin\Motiva.exe
UninstallDisplayName={#AppName}
WizardStyle=modern
WizardImageFile=assets\motiva-installer-welcome.png
WizardSmallImageFile=assets\motiva-installer-banner.png
Compression=lzma2/max
SolidCompression=yes
CloseApplications=force
; No LicenseFile: the repository has no license file, and none is invented.

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Messages]
SetupWindowTitle=Motiva Setup
FinishedHeadingLabel=Motiva is ready
FinishedLabelNoIcons=Your desktop is ready for motion.
FinishedLabel=Your desktop is ready for motion.

[Files]
; Installer-only UI bitmaps first: they sit at the start of the solid stream, so
; extracting them at startup does not have to decompress the app payload.
Source: "assets\motiva-installer-finish.bmp"; DestDir: "{tmp}"; Flags: dontcopy
Source: "assets\ui\*.bmp"; DestDir: "{tmp}"; Flags: dontcopy
; Uninstaller UI assets (the uninstaller cannot read the installer's embedded files). Listed before
; the app payload so the installer's "Copying application" step ordering is unchanged.
Source: "assets\ui\btn-*.bmp"; DestDir: "{app}\uninstall-ui"; Flags: ignoreversion
Source: "assets\ui\progress-*.bmp"; DestDir: "{app}\uninstall-ui"; Flags: ignoreversion
Source: "assets\uninstall-*.bmp"; DestDir: "{app}\uninstall-ui"; Flags: ignoreversion
Source: "{#StagingDir}\*"; DestDir: "{app}"; Flags: recursesubdirs createallsubdirs ignoreversion

[Icons]
; Always created (no user choice): the Start Menu entry is what Windows Search
; indexes. Target is the installed launcher; the icon is the real binary's.
Name: "{autoprograms}\{#AppName}"; Filename: "{app}\Motiva.exe"; WorkingDir: "{app}"; IconFilename: "{app}\resources\bin\Motiva.exe"

[Run]
Filename: "{app}\Motiva.exe"; Description: "Launch Motiva"; Flags: nowait postinstall skipifsilent

[Code]
const
  // Colours are BGR. Must match the RGB(12,14,30) the control bitmaps are drawn on.
  clBg      = $1E0E0C;
  clText    = $FFFFFF;
  clMuted   = $E6C9BC;
  clDim     = $A57A6E;
  clAccent  = $FFC25A;
  clGood    = $BEE150;
  clPanel   = $2C1815;
  clFrame   = $786246;
  BM_CLICK  = $F5;

  BTN_NEXT = 0;
  BTN_BACK = 1;
  BTN_CANCEL = 2;
  BTN_BROWSE = 3;

function SetTimer(hWnd: LongWord; nIDEvent, uElapse: LongWord; lpTimerFunc: LongWord): LongWord; external 'SetTimer@user32.dll stdcall';
function GetCursorPos(var P: TPoint): Boolean; external 'GetCursorPos@user32.dll stdcall';
function ScreenToClient(hWnd: LongWord; var P: TPoint): Boolean; external 'ScreenToClient@user32.dll stdcall';
function GetKeyState(nVirtKey: Integer): SmallInt; external 'GetKeyState@user32.dll stdcall';
function PostMessage(hWnd: LongWord; Msg: LongWord; wParam, lParam: LongInt): Boolean; external 'PostMessageW@user32.dll stdcall';
function KillTimer(hWnd: LongWord; uIDEvent: LongWord): Boolean; external 'KillTimer@user32.dll stdcall';
function SetStretchBltMode(hdc: LongWord; iMode: Integer): Integer; external 'SetStretchBltMode@gdi32.dll stdcall';
function StretchBlt(hdcDest: LongWord; xDest, yDest, wDest, hDest: Integer; hdcSrc: LongWord; xSrc, ySrc, wSrc, hSrc: Integer; rop: LongWord): Boolean; external 'StretchBlt@gdi32.dll stdcall';

var
  PowerPage, OptionsPage: TWizardPage;
  DirEditBox: TNewEdit;
  DirFrame: TPanel;
  PowerLbl, LaunchLbl, StatusBarLbl: TNewStaticText;

  // custom buttons
  BImg: array[0..3] of TBitmapImage;
  BNative: array[0..2] of TNewButton;
  BCap: array[0..3] of String;
  BShown: array[0..3] of String;
  BaseBtn: array[0..7] of TBitmap;

  // custom checkboxes: 0 = power acknowledgement, 1 = launch Motiva
  ChkImg: array[0..1] of TBitmapImage;
  ChkOn: array[0..1] of Boolean;
  ChkShown: array[0..1] of Integer;
  ChkBmp: array[0..3] of TBitmap;

  // installation page
  TrackImg, FillImg: TBitmapImage;
  FillL, FillM, FillR: TBitmap;
  PctLbl, LiveLbl: TNewStaticText;
  StepG, StepT: array[0..5] of TNewStaticText;
  TrackW: Integer;
  OrigNbTop, OrigNbHeight: Integer;
  InstallStarted, FilesDone, PostInstallDone: Boolean;
  SeenCat: array[0..3] of Boolean;
  CurCat, LastPct: Integer;

// ---------------------------------------------------------------- helpers

function CursorInside(C: TControl): Boolean;
var P: TPoint;
begin
  Result := False;
  if (C = nil) or (not C.Visible) then Exit;
  GetCursorPos(P);
  ScreenToClient(C.Parent.Handle, P);
  Result := (P.X >= C.Left) and (P.X < C.Left + C.Width) and (P.Y >= C.Top) and (P.Y < C.Top + C.Height);
end;

function HoverState(C: TControl; Enabled: Boolean): Integer;
begin
  // 0 normal, 1 hover, 2 pressed, 3 disabled
  if not Enabled then Result := 3
  else if CursorInside(C) then begin
    if GetKeyState(1) < 0 then Result := 2 else Result := 1;
  end else Result := 0;
end;


var
  PrevDown: array[0..7] of Boolean;

// Click = press then release while the pointer is over the control. Detected
// here (in the UI timer) instead of via OnClick, which bitmap controls do
// not reliably raise.
function ClickEdge(Id: Integer; C: TControl): Boolean;
var Down: Boolean;
begin
  Down := CursorInside(C) and (GetKeyState(1) < 0);
  Result := PrevDown[Id] and (not Down) and CursorInside(C);
  PrevDown[Id] := Down;
end;

procedure LoadTmpBmp(B: TBitmap; const Name: String);
begin
  ExtractTemporaryFile(Name);
  B.LoadFromFile(ExpandConstant('{tmp}\' + Name));
end;

function MakeRect(L, T, R, B: Integer): TRect;
begin
  Result.Left := L; Result.Top := T; Result.Right := R; Result.Bottom := B;
end;

// The control art is authored at 2x; scaling it to the wizard's real DPI with
// HALFTONE keeps edges smooth (and the button text, drawn afterwards at the
// final size, crisp).
function ScaledBmp(Src: TBitmap; W, H: Integer): TBitmap;
begin
  Result := TBitmap.Create;
  Result.Width := W;
  Result.Height := H;
  SetStretchBltMode(Result.Canvas.Handle, 4);
  StretchBlt(Result.Canvas.Handle, 0, 0, W, H, Src.Canvas.Handle, 0, 0, Src.Width, Src.Height, $CC0020);
end;

// ---------------------------------------------------------------- buttons

procedure PaintButton(I, State: Integer);
var B: TBitmap; Kind, Tw, Th: Integer; Sig: String;
begin
  Sig := IntToStr(State) + '|' + BCap[I];
  if Sig = BShown[I] then Exit;
  BShown[I] := Sig;
  if I = BTN_NEXT then Kind := 0 else Kind := 1;
  B := ScaledBmp(BaseBtn[Kind * 4 + State], BImg[I].Width, BImg[I].Height);
  try
    B.Canvas.Font.Name := 'Segoe UI Semibold';
    B.Canvas.Font.Size := 10;
    B.Canvas.Brush.Style := bsClear;
    if State = 3 then B.Canvas.Font.Color := $82705A
    else if (Kind = 0) or (State > 0) then B.Canvas.Font.Color := clWhite
    else B.Canvas.Font.Color := $F0D8CC;
    Tw := B.Canvas.TextWidth(BCap[I]);
    Th := B.Canvas.TextHeight(BCap[I]);
    B.Canvas.TextOut((B.Width - Tw) div 2, (B.Height - Th) div 2 - 1, BCap[I]);
    BImg[I].Bitmap.Assign(B);
  finally
    B.Free;
  end;
end;

procedure NavClick(I: Integer);
begin
  // Forward to Inno's own button so validation, navigation and the
  // cancel confirmation all stay Inno's. A disabled button ignores BM_CLICK.
  PostMessage(BNative[I].Handle, BM_CLICK, 0, 0);
end;

procedure NextClick(Sender: TObject); begin NavClick(BTN_NEXT); end;
procedure BackClick(Sender: TObject); begin NavClick(BTN_BACK); end;
procedure CancelClick(Sender: TObject); begin NavClick(BTN_CANCEL); end;

procedure BrowseClick(Sender: TObject);
var S: String;
begin
  S := DirEditBox.Text;
  if BrowseForFolder('Choose where to install Motiva', S, True) then
    DirEditBox.Text := S;
end;

function MakeButton(Parent: TWinControl; Kind: Integer): TBitmapImage;
begin
  Result := TBitmapImage.Create(WizardForm);
  Result.Parent := Parent;
  Result.Stretch := False;
  Result.Cursor := crHand;
  if Kind = 0 then Result.Width := ScaleX(150) else Result.Width := ScaleX(110);
  Result.Height := ScaleY(40);
end;

procedure LayoutNav;
var I, X: Integer; Order: array[0..2] of Integer;
begin
  Order[0] := BTN_NEXT; Order[1] := BTN_BACK; Order[2] := BTN_CANCEL;
  X := WizardForm.ClientWidth - ScaleX(24);
  for I := 0 to 2 do begin
    BImg[Order[I]].Visible := BNative[Order[I]].Visible;
    if BImg[Order[I]].Visible then begin
      BImg[Order[I]].Left := X - BImg[Order[I]].Width;
      X := BImg[Order[I]].Left - ScaleX(10);
    end;
  end;
end;

procedure SyncNavButtons;
var I: Integer;
begin
  LayoutNav;
  for I := 0 to 2 do
    if BImg[I].Visible then PaintButton(I, HoverState(BImg[I], BNative[I].Enabled));
  if (OptionsPage <> nil) and (WizardForm.CurPageID = OptionsPage.ID) then
    PaintButton(BTN_BROWSE, HoverState(BImg[BTN_BROWSE], True));
end;

// ---------------------------------------------------------------- checkboxes

procedure PaintCheck(I: Integer);
var S: Integer;
begin
  if ChkOn[I] then S := 2 else S := 0;
  if CursorInside(ChkImg[I]) then S := S + 1;
  if S <> ChkShown[I] then begin
    ChkShown[I] := S;
    ChkImg[I].Bitmap.Assign(ChkBmp[S]);
  end;
end;

procedure ToggleCheck(I: Integer);
begin
  ChkOn[I] := not ChkOn[I];
  if I = 0 then begin
    WizardForm.NextButton.Enabled := ChkOn[0] or WizardSilent;
  end else begin
    if WizardForm.RunList.Items.Count > 0 then
      WizardForm.RunList.Checked[0] := ChkOn[1];
  end;
  PaintCheck(I);
end;

procedure PowerToggle(Sender: TObject); begin ToggleCheck(0); end;
procedure LaunchToggle(Sender: TObject); begin ToggleCheck(1); end;

function MakeCheck(Parent: TWinControl; Idx: Integer): TBitmapImage;
begin
  Result := TBitmapImage.Create(WizardForm);
  Result.Parent := Parent;
  Result.Stretch := False;
  Result.Width := ScaleX(24);
  Result.Height := ScaleY(24);
  Result.Cursor := crHand;
  ChkShown[Idx] := -1;
end;

// ---------------------------------------------------------------- labels

function AddLabel(Parent: TWinControl; const Caption: String; Left, Top, Width, Size: Integer;
  Bold: Boolean; Color: TColor; const FontName: String): TNewStaticText;
begin
  Result := TNewStaticText.Create(WizardForm);
  Result.Parent := Parent;
  Result.Left := Left;
  Result.Top := Top;
  Result.Width := Width;
  Result.AutoSize := True;
  Result.WordWrap := True;
  Result.Font.Name := FontName;
  Result.Font.Size := Size;
  if Bold then Result.Font.Style := [fsBold];
  Result.Font.Color := Color;
  Result.Caption := Caption;
end;

procedure CenterLabel(L: TNewStaticText; AreaWidth: Integer);
begin
  L.WordWrap := False;
  L.Left := (AreaWidth - L.Width) div 2;
end;

procedure PowerLabelClick(Sender: TObject); begin ToggleCheck(0); end;
procedure LaunchLabelClick(Sender: TObject); begin ToggleCheck(1); end;

// ---------------------------------------------------------------- pages

procedure BuildPowerPage;
var Head, B1, B2, B3: TNewStaticText; Y, W: Integer;
begin
  W := PowerPage.SurfaceWidth;
  Head := AddLabel(PowerPage.Surface, 'Power && Battery Usage', 0, 0, W, 13, True, clAccent, 'Segoe UI');
  Y := Head.Top + Head.Height + ScaleY(10);
  B1 := AddLabel(PowerPage.Surface,
    'Motiva uses video and animated content to display motion on your desktop. Depending on the selected media, ' +
    'resolution, frame rate, hardware, and system configuration, animated wallpapers may consume significantly more ' +
    'CPU/GPU power than a traditional static wallpaper.', 0, Y, W, 10, False, clMuted, 'Segoe UI');
  Y := B1.Top + B1.Height + ScaleY(10);
  B2 := AddLabel(PowerPage.Surface,
    'When running on battery power, this can result in higher battery usage and reduced battery runtime.',
    0, Y, W, 10, False, clMuted, 'Segoe UI');
  Y := B2.Top + B2.Height + ScaleY(10);
  B3 := AddLabel(PowerPage.Surface,
    'Motiva provides settings that allow you to control whether video wallpaper remains active while your device is ' +
    'running on battery. Please review these settings after installation if battery life is important to you.',
    0, Y, W, 10, False, clMuted, 'Segoe UI');
  Y := B3.Top + B3.Height + ScaleY(22);

  ChkImg[0] := MakeCheck(PowerPage.Surface, 0);
  ChkImg[0].Left := 0;
  ChkImg[0].Top := Y;
  PowerLbl := AddLabel(PowerPage.Surface,
    'I understand that animated/video wallpapers may consume more power and may result in higher battery usage.',
    ScaleX(36), Y, W - ScaleX(36), 10, False, clText, 'Segoe UI');
  PowerLbl.Top := Y + ScaleY(2);
  PowerLbl.Cursor := crHand;
end;

procedure BuildOptionsPage;
var L1, L2: TNewStaticText; Y, W: Integer;
begin
  W := OptionsPage.SurfaceWidth;
  L1 := AddLabel(OptionsPage.Surface, 'Installation Location', 0, 0, W, 13, True, clAccent, 'Segoe UI');
  Y := L1.Top + L1.Height + ScaleY(6);
  L2 := AddLabel(OptionsPage.Surface,
    'Motiva installs for your Windows account and does not need administrator rights.',
    0, Y, W, 10, False, clMuted, 'Segoe UI');
  Y := L2.Top + L2.Height + ScaleY(24);

  DirFrame := TPanel.Create(WizardForm);
  DirFrame.Parent := OptionsPage.Surface;
  DirFrame.BevelOuter := bvNone;
  DirFrame.ParentBackground := False;
  DirFrame.Color := $824840;
  DirFrame.Left := 0;
  DirFrame.Top := Y;
  DirFrame.Width := W - ScaleX(124);
  DirFrame.Height := ScaleY(40);

  DirEditBox := TNewEdit.Create(WizardForm);
  DirEditBox.Parent := DirFrame;
  DirEditBox.BorderStyle := bsNone;
  DirEditBox.Color := clPanel;
  DirEditBox.Font.Name := 'Segoe UI';
  DirEditBox.Font.Size := 10;
  DirEditBox.Font.Color := clText;
  DirEditBox.Left := ScaleX(1);
  DirEditBox.Top := ScaleY(1);
  DirEditBox.Width := DirFrame.Width - ScaleX(2);
  DirEditBox.Text := WizardForm.DirEdit.Text;
  DirEditBox.Top := (DirFrame.Height - DirEditBox.Height) div 2;
  DirEditBox.SelLength := 0;

  BImg[BTN_BROWSE] := MakeButton(OptionsPage.Surface, 1);
  BImg[BTN_BROWSE].Left := DirFrame.Width + ScaleX(14);
  BImg[BTN_BROWSE].Top := Y;
  BCap[BTN_BROWSE] := 'Browse...';
  BShown[BTN_BROWSE] := '';
end;

// Fill = two rounded caps + a stretched middle, so the ends stay round at any width.
procedure PaintFill(W: Integer);
var B: TBitmap; H, Cap: Integer;
begin
  H := ScaleY(8);
  Cap := H div 2;
  B := TBitmap.Create;
  try
    B.Width := W;
    B.Height := H;
    SetStretchBltMode(B.Canvas.Handle, 4);
    StretchBlt(B.Canvas.Handle, 0, 0, Cap, H, FillL.Canvas.Handle, 0, 0, FillL.Width, FillL.Height, $CC0020);
    if W > Cap * 2 then
      StretchBlt(B.Canvas.Handle, Cap, 0, W - Cap * 2, H, FillM.Canvas.Handle, 0, 0, FillM.Width, FillM.Height, $CC0020);
    StretchBlt(B.Canvas.Handle, W - Cap, 0, Cap, H, FillR.Canvas.Handle, 0, 0, FillR.Width, FillR.Height, $CC0020);
    FillImg.Width := W;
    FillImg.Bitmap.Assign(B);
  finally
    B.Free;
  end;
end;

procedure BuildInstallingPage;
var Pg: TNewNotebookPage; PW, I, Y, TX: Integer; T: TNewStaticText; Tmp: TBitmap;
  Names: array[0..5] of String;
begin
  Pg := WizardForm.InstallingPage;
  PW := Pg.Width;
  WizardForm.ProgressGauge.Visible := False;
  WizardForm.StatusLabel.Visible := False;
  WizardForm.FilenameLabel.Visible := False;

  T := AddLabel(Pg, 'Installing Motiva', 0, ScaleY(34), PW, 24, False, clText, 'Segoe UI Light');
  CenterLabel(T, PW);
  T := AddLabel(Pg, 'Bringing motion to your Windows desktop.', 0, ScaleY(80), PW, 11, False, clMuted, 'Segoe UI');
  CenterLabel(T, PW);

  TrackW := (PW * 90) div 100;
  TX := (PW - TrackW) div 2;
  Y := ScaleY(130);
  TrackImg := TBitmapImage.Create(WizardForm);
  TrackImg.Parent := Pg;
  TrackImg.Stretch := False;
  TrackImg.SetBounds(TX, Y, TrackW, ScaleY(14));
  Tmp := TBitmap.Create;
  LoadTmpBmp(Tmp, 'progress-track.bmp');
  TrackImg.Bitmap.Assign(ScaledBmp(Tmp, TrackW, ScaleY(14)));
  Tmp.Free;
  FillL := TBitmap.Create; FillM := TBitmap.Create; FillR := TBitmap.Create;
  LoadTmpBmp(FillL, 'progress-fill-l.bmp');
  LoadTmpBmp(FillM, 'progress-fill-m.bmp');
  LoadTmpBmp(FillR, 'progress-fill-r.bmp');
  FillImg := TBitmapImage.Create(WizardForm);
  FillImg.Parent := Pg;
  FillImg.Stretch := False;
  FillImg.SetBounds(TX + ScaleX(3), Y + ScaleY(3), ScaleX(8), ScaleY(8));
  PaintFill(ScaleX(8));
  FillImg.Visible := False;
  PctLbl := AddLabel(Pg, '0%', TX, Y - ScaleY(26), ScaleX(60), 10, True, clAccent, 'Segoe UI');
  PctLbl.Left := TX + TrackW - PctLbl.Width;

  Names[0] := 'Preparing installation';
  Names[1] := 'Copying application';
  Names[2] := 'Installing plugins';
  Names[3] := 'Installing Qt runtime';
  Names[4] := 'Creating Start Menu shortcut';
  Names[5] := 'Finalizing installation';
  Y := ScaleY(172);
  for I := 0 to 5 do begin
    StepG[I] := AddLabel(Pg, #$25CB, TX + ScaleX(6), Y, ScaleX(24), 11, False, clDim, 'Segoe UI Symbol');
    StepG[I].WordWrap := False;
    StepT[I] := AddLabel(Pg, Names[I], TX + ScaleX(38), Y + ScaleY(1), TrackW - ScaleX(44), 11, False, clDim, 'Segoe UI');
    StepT[I].WordWrap := False;
    Y := Y + ScaleY(26);
  end;
  LiveLbl := AddLabel(Pg, 'Preparing installation...', TX, Y + ScaleY(10), TrackW, 10, False, clMuted, 'Segoe UI');
  LiveLbl.WordWrap := False;
end;

// ---------------------------------------------------------------- status

function StepState(I: Integer): Integer; // 0 pending, 1 active, 2 done
begin
  Result := 0;
  case I of
    0: if InstallStarted then Result := 2 else Result := 1;
    1..3:
      if (not FilesDone) and (CurCat = I) then Result := 1
      else if SeenCat[I] then Result := 2;
    4: if PostInstallDone then Result := 2 else if FilesDone then Result := 1;
    5: if PostInstallDone then Result := 1;
  end;
end;

procedure RefreshSteps;
var I, S: Integer;
begin
  for I := 0 to 5 do begin
    S := StepState(I);
    case S of
      2: begin StepG[I].Caption := #$2713; StepG[I].Font.Color := clGood; StepT[I].Font.Color := clMuted; StepT[I].Font.Style := []; end;
      1: begin StepG[I].Caption := #$2192; StepG[I].Font.Color := clAccent; StepT[I].Font.Color := clText; StepT[I].Font.Style := [fsBold]; end;
    else begin
      StepG[I].Caption := #$25CB;
      StepG[I].Font.Color := clDim;
      StepT[I].Font.Color := clDim;
      StepT[I].Font.Style := [];
    end;
    end;
  end;
end;

function CategoryOf(const Path: String): Integer;
var L: String;
begin
  L := Lowercase(Path);
  if Pos('\resources\plugins\', L) > 0 then Result := 2
  else if Pos('\resources\qt\', L) > 0 then Result := 3
  else Result := 1;
end;

function ShortPath(const Path: String): String;
var P: Integer; L: String;
begin
  L := Lowercase(Path);
  P := Pos('\motiva\', L);
  if P > 0 then Result := Copy(Path, P + 8, Length(Path)) else Result := Path;
  if Length(Result) > 62 then Result := '...' + Copy(Result, Length(Result) - 58, 60);
end;

procedure SetStatusBar(const Txt: String);
begin
  StatusBarLbl.Caption := #$25CF + '  Motiva  ' + #$2022 + '  ' + Txt;
end;

procedure CurInstallProgressChanged(CurProgress, MaxProgress: Integer);
var W: Int64; Pct: Integer; F: String;
begin
  if MaxProgress <= 0 then Exit;
  Pct := Integer((Int64(CurProgress) * 100) div MaxProgress);
  W := (Int64(CurProgress) * (TrackW - ScaleX(6))) div MaxProgress;
  if W < ScaleX(6) then W := ScaleX(6);
  if Integer(W) <> FillImg.Width then PaintFill(Integer(W));
  FillImg.Visible := CurProgress > 0;
  if Pct <> LastPct then begin
    LastPct := Pct;
    PctLbl.Caption := IntToStr(Pct) + '%';
    PctLbl.Left := TrackImg.Left + TrackW - PctLbl.Width;
  end;
  FilesDone := CurProgress >= MaxProgress;
  F := WizardForm.FilenameLabel.Caption;
  if (F <> '') and (not FilesDone) then begin
    CurCat := CategoryOf(F);
    SeenCat[CurCat] := True;
  end;
  if FilesDone then LiveLbl.Caption := 'Creating Start Menu shortcut...'
  else case CurCat of
    3: LiveLbl.Caption := 'Installing Qt runtime...  ' + ShortPath(F);
    2: LiveLbl.Caption := 'Installing plugins...  ' + ShortPath(F);
  else
    LiveLbl.Caption := 'Copying Motiva...  ' + ShortPath(F);
  end;
  RefreshSteps;
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssInstall then begin
    InstallStarted := True;
    LiveLbl.Caption := 'Copying Motiva...';
    RefreshSteps;
  end else if CurStep = ssPostInstall then begin
    FilesDone := True;
    PostInstallDone := True;
    LiveLbl.Caption := 'Finalizing installation...';
    PctLbl.Caption := '100%';
    PctLbl.Left := TrackImg.Left + TrackW - PctLbl.Width;
    PaintFill(TrackW - ScaleX(6));
    RefreshSteps;
  end;
end;

// ---------------------------------------------------------------- timer / wizard

procedure UiTick(H: LongWord; Msg: LongWord; IdEvent: LongWord; Time: LongWord);
var I: Integer; Clicked: Boolean;
begin
  try
    SyncNavButtons;
    for I := 0 to 2 do
      if BImg[I].Visible then begin
        Clicked := ClickEdge(I, BImg[I]);
        if Clicked and BNative[I].Enabled then NavClick(I);
      end;
    if (OptionsPage <> nil) and (WizardForm.CurPageID = OptionsPage.ID) then
      if ClickEdge(BTN_BROWSE, BImg[BTN_BROWSE]) then BrowseClick(nil);
    if (PowerPage <> nil) and (WizardForm.CurPageID = PowerPage.ID) then begin
      if ClickEdge(4, ChkImg[0]) then ToggleCheck(0);
      if ClickEdge(6, PowerLbl) then ToggleCheck(0);
      PaintCheck(0);
    end;
    if WizardForm.CurPageID = wpFinished then begin
      if ClickEdge(5, ChkImg[1]) then ToggleCheck(1);
      if ClickEdge(7, LaunchLbl) then ToggleCheck(1);
      PaintCheck(1);
    end;
  except
    Log('UiTick: ' + GetExceptionMessage);
  end;
end;

procedure InitializeWizard;
var I, J: Integer; FinishImg: String; HeroH: Integer;
begin
  // Grow the window slightly so the button strip has room for 40px buttons + status bar.
  WizardForm.ClientHeight := WizardForm.ClientHeight + ScaleY(26);
  WizardForm.Font.Name := 'Segoe UI';
  WizardForm.Color := clBg;
  WizardForm.MainPanel.Color := clPanel;
  WizardForm.PageNameLabel.Font.Color := clText;
  WizardForm.PageDescriptionLabel.Font.Color := clMuted;
  WizardForm.InnerPage.Color := clBg;
  WizardForm.WelcomePage.Color := clBg;
  WizardForm.FinishedPage.Color := clBg;
  WizardForm.Bevel.Visible := False;
  WizardForm.Bevel1.Visible := False;
  // Leave a taller strip for the 40px custom buttons + status bar.
  WizardForm.OuterNotebook.Height := WizardForm.ClientHeight - WizardForm.OuterNotebook.Top - ScaleY(72);
  OrigNbTop := WizardForm.InnerNotebook.Top;
  OrigNbHeight := WizardForm.InnerNotebook.Height;

  // bitmaps for the custom controls
  for I := 0 to 3 do begin
    BaseBtn[I] := TBitmap.Create;
    BaseBtn[4 + I] := TBitmap.Create;
    ChkBmp[I] := TBitmap.Create;
  end;
  for I := 0 to 3 do begin
    LoadTmpBmp(BaseBtn[I], 'btn-primary-' + IntToStr(I) + '.bmp');
    LoadTmpBmp(BaseBtn[4 + I], 'btn-secondary-' + IntToStr(I) + '.bmp');
  end;
  LoadTmpBmp(ChkBmp[0], 'check-off.bmp');
  LoadTmpBmp(ChkBmp[1], 'check-off-hover.bmp');
  LoadTmpBmp(ChkBmp[2], 'check-on.bmp');
  LoadTmpBmp(ChkBmp[3], 'check-on-hover.bmp');
  for I := 0 to 3 do ChkBmp[I] := ScaledBmp(ChkBmp[I], ScaleX(24), ScaleY(24));

  // Welcome hero: full-bleed image carries wordmark + tagline.
  WizardForm.WizardBitmapImage.Left := 0;
  WizardForm.WizardBitmapImage.Top := 0;
  WizardForm.WizardBitmapImage.Width := WizardForm.WelcomePage.Width;
  WizardForm.WizardBitmapImage.Height := WizardForm.WelcomePage.Height;
  WizardForm.WizardBitmapImage.Stretch := True;
  WizardForm.WelcomeLabel1.Visible := False;
  WizardForm.WelcomeLabel2.Visible := False;

  // Finish hero + custom "Launch Motiva" checkbox.
  ExtractTemporaryFile('motiva-installer-finish.bmp');
  FinishImg := ExpandConstant('{tmp}\motiva-installer-finish.bmp');
  WizardForm.WizardBitmapImage2.Bitmap.LoadFromFile(FinishImg);
  HeroH := (WizardForm.FinishedPage.Width * 2) div 5;
  WizardForm.WizardBitmapImage2.Left := 0;
  WizardForm.WizardBitmapImage2.Top := 0;
  WizardForm.WizardBitmapImage2.Width := WizardForm.FinishedPage.Width;
  WizardForm.WizardBitmapImage2.Height := HeroH;
  WizardForm.WizardBitmapImage2.Stretch := True;
  WizardForm.FinishedHeadingLabel.Visible := False;
  WizardForm.FinishedLabel.Visible := False;
  WizardForm.RunList.Left := -3000; // replaced by the custom checkbox; still holds the real run state
  ChkImg[1] := MakeCheck(WizardForm.FinishedPage, 1);
  ChkOn[1] := True;
  LaunchLbl := AddLabel(WizardForm.FinishedPage, 'Launch Motiva', 0, 0, ScaleX(200), 11, False, clText, 'Segoe UI');
  LaunchLbl.WordWrap := False;
  LaunchLbl.Cursor := crHand;
  ChkImg[1].Left := (WizardForm.FinishedPage.Width - (ScaleX(36) + LaunchLbl.Width)) div 2;
  ChkImg[1].Top := HeroH + ScaleY(34);
  LaunchLbl.Left := ChkImg[1].Left + ScaleX(34);
  LaunchLbl.Top := ChkImg[1].Top + ScaleY(2);

  // Custom pages
  PowerPage := CreateCustomPage(wpWelcome, 'Important Power Usage Notice', 'Please review this before installing Motiva.');
  OptionsPage := CreateCustomPage(PowerPage.ID, 'Installation Location', 'Choose where Motiva is installed.');
  BuildPowerPage;
  BuildOptionsPage;
  ChkOn[0] := False;

  // Custom navigation buttons; the native ones are parked off-screen (their
  // Visible/Enabled state, which Inno drives per page, is mirrored onto ours).
  BNative[BTN_NEXT] := WizardForm.NextButton;
  BNative[BTN_BACK] := WizardForm.BackButton;
  BNative[BTN_CANCEL] := WizardForm.CancelButton;
  BImg[BTN_NEXT] := MakeButton(WizardForm, 0);
  BImg[BTN_BACK] := MakeButton(WizardForm, 1);
  BImg[BTN_CANCEL] := MakeButton(WizardForm, 1);
  BCap[BTN_NEXT] := 'Next';
  BCap[BTN_BACK] := #$2190 + '  Back';
  BCap[BTN_CANCEL] := 'Cancel';
  for I := 0 to 3 do BShown[I] := '';
  for I := 0 to 2 do begin
    BImg[I].Top := WizardForm.ClientHeight - ScaleY(58);
    BNative[I].Left := -3000;
  end;

  StatusBarLbl := AddLabel(WizardForm, '', ScaleX(28), WizardForm.ClientHeight - ScaleY(48), ScaleX(300), 9, False, clDim, 'Segoe UI');
  StatusBarLbl.WordWrap := False;
  SetStatusBar('Welcome');

  BuildInstallingPage;
  CurCat := -1;
  LastPct := -1;
  for J := 0 to 3 do SeenCat[J] := False;
  RefreshSteps;

  SetTimer(0, 0, 30, CreateCallback(@UiTick));
end;

procedure CurPageChanged(CurPageID: Integer);
var Installing: Boolean;
begin
  Installing := CurPageID = wpInstalling;
  // Installing page is full-bleed (no header strip).
  WizardForm.MainPanel.Visible := not Installing;
  if Installing then begin
    WizardForm.InnerNotebook.Top := 0;
    WizardForm.InnerNotebook.Height := WizardForm.InnerPage.Height;
  end else begin
    WizardForm.InnerNotebook.Top := OrigNbTop;
    WizardForm.InnerNotebook.Height := OrigNbHeight;
  end;

  BCap[BTN_BACK] := #$2190 + '  Back';
  BCap[BTN_NEXT] := 'Next';
  if CurPageID = wpWelcome then begin
    BCap[BTN_NEXT] := 'Get Started  ' + #$2192;
    SetStatusBar('Welcome');
  end else if CurPageID = PowerPage.ID then begin
    BCap[BTN_NEXT] := 'Continue  ' + #$2192;
    WizardForm.NextButton.Enabled := ChkOn[0] or WizardSilent;
    SetStatusBar('Power notice');
  end else if CurPageID = OptionsPage.ID then begin
    BCap[BTN_NEXT] := 'Install  ' + #$2192;
    WizardForm.NextButton.Enabled := True;
    DirEditBox.SelLength := 0;
    WizardForm.ActiveControl := WizardForm.NextButton;
    SetStatusBar('Location');
  end else if Installing then begin
    SetStatusBar('Installing Motiva  ' + #$2022 + '  Please wait...');
  end else if CurPageID = wpFinished then begin
    BCap[BTN_NEXT] := 'Finish';
    SetStatusBar('Installation complete');
    WizardForm.RunList.Left := -3000;
    WizardForm.RunList.Visible := True;
    if WizardForm.RunList.Items.Count > 0 then WizardForm.RunList.Checked[0] := ChkOn[1];
    PostInstallDone := True;
    RefreshSteps;
  end;
  SyncNavButtons;
end;

function NextButtonClick(CurPageID: Integer): Boolean;
begin
  Result := True;
  if CurPageID = PowerPage.ID then begin
    // Interactive acknowledgement gate (the button is also disabled until
    // ticked). Unattended /SILENT installs have no one to ask, so they pass.
    Result := ChkOn[0] or WizardSilent;
    if not Result then MsgBox('Please confirm that you understand the power usage notice to continue.', mbInformation, MB_OK);
  end
  else if CurPageID = OptionsPage.ID then begin
    if Trim(DirEditBox.Text) = '' then begin
      MsgBox('Please choose an installation folder.', mbError, MB_OK);
      Result := False;
    end else
      WizardForm.DirEdit.Text := DirEditBox.Text;
  end;
end;

function StopMotiva: Integer;
var R: Integer;
begin
  Exec(ExpandConstant('{sys}\taskkill.exe'), '/F /IM Motiva.exe', '', SW_HIDE, ewWaitUntilTerminated, R);
  Result := R;
end;

function PrepareToInstall(var NeedsRestart: Boolean): String;
begin
  StopMotiva;
  Result := '';
end;

// Removes ONLY Motiva's own Explorer verb (MotivaSetBackground) under each
// per-user SystemFileAssociations extension, and its autostart value.
// User settings (HKCU\Software\Motiva), recovery state and media are kept.
procedure CleanMotivaShellRegistration;
var Names: TArrayOfString; I: Integer; Base: String;
begin
  Base := 'Software\Classes\SystemFileAssociations';
  if RegGetSubkeyNames(HKCU, Base, Names) then
    for I := 0 to GetArrayLength(Names) - 1 do
      if RegKeyExists(HKCU, Base + '\' + Names[I] + '\shell\MotivaSetBackground') then
        RegDeleteKeyIncludingSubkeys(HKCU, Base + '\' + Names[I] + '\shell\MotivaSetBackground');
  RegDeleteValue(HKCU, 'Software\Microsoft\Windows\CurrentVersion\Run', 'Motiva');
end;

// ================================================================ Uninstaller UI
// Same Motiva design language as the installer. The uninstaller cannot use
// ExtractTemporaryFile, so its bitmaps are read from {app}\uninstall-ui
// (installed alongside the app) and loaded into memory before anything is removed.
//
// Flow: a normal launch shows the Motiva welcome dialog; on confirm it relaunches
// itself with /SILENT /MOTIVAUI so Inno's own confirm / "successfully removed" message
// boxes never appear, and the Motiva progress form + completion dialog are shown
// instead. /VERYSILENT and scripted /SILENT runs (no /MOTIVAUI) show no dialogs.

var
  UnBase: array[0..7] of TBitmap;
  UnFillL, UnFillM, UnFillR: TBitmap;
  UnHeroWelcome, UnHeroDone: TBitmap;
  UnAssetsReady: Boolean;
  UnMode: Integer;              // 0 none, 1 dialog, 2 progress form
  UnTimerId: LongWord;
  UnPrev: array[0..3] of Boolean;
  UnDlg: TSetupForm;
  UnDlgOk: Boolean;
  UnDlgImg: array[0..1] of TBitmapImage;   // 0 primary, 1 secondary
  UnDlgCap, UnDlgShown: array[0..1] of String;
  UpTrack, UpFill, UpCancelImg: TBitmapImage;
  UpPct, UpLive, UpStatus: TNewStaticText;
  UpG, UpT: array[0..3] of TNewStaticText;
  UpTrackW, UpLastW, UpStage: Integer;
  UpFormAlive: Boolean;   // Inno destroys the progress form before usPostUninstall
  UpCancelShown: String;

function HasParam(const P: String): Boolean;
var I: Integer;
begin
  Result := False;
  for I := 1 to ParamCount do
    if CompareText(ParamStr(I), P) = 0 then Result := True;
end;

function UnAsset(const Name: String): String;
begin
  Result := ExpandConstant('{app}\uninstall-ui\' + Name);
end;

procedure UnLoadAssets;
var I: Integer;
begin
  if UnAssetsReady then Exit;
  try
    for I := 0 to 3 do begin
      UnBase[I] := TBitmap.Create;
      UnBase[I].LoadFromFile(UnAsset('btn-primary-' + IntToStr(I) + '.bmp'));
      UnBase[4 + I] := TBitmap.Create;
      UnBase[4 + I].LoadFromFile(UnAsset('btn-secondary-' + IntToStr(I) + '.bmp'));
    end;
    UnFillL := TBitmap.Create; UnFillL.LoadFromFile(UnAsset('progress-fill-l.bmp'));
    UnFillM := TBitmap.Create; UnFillM.LoadFromFile(UnAsset('progress-fill-m.bmp'));
    UnFillR := TBitmap.Create; UnFillR.LoadFromFile(UnAsset('progress-fill-r.bmp'));
    UnHeroWelcome := TBitmap.Create; UnHeroWelcome.LoadFromFile(UnAsset('uninstall-welcome.bmp'));
    UnHeroDone := TBitmap.Create; UnHeroDone.LoadFromFile(UnAsset('uninstall-done.bmp'));
    UnAssetsReady := True;
  except
    UnAssetsReady := False; // fall back to Inno's default uninstall UI
  end;
end;

function UnClickEdge(Id: Integer; C: TControl): Boolean;
var Down: Boolean;
begin
  Down := CursorInside(C) and (GetKeyState(1) < 0);
  Result := UnPrev[Id] and (not Down) and CursorInside(C);
  UnPrev[Id] := Down;
end;

procedure UnPaintBtn(Img: TBitmapImage; Kind, State: Integer; const Cap: String; var Shown: String);
var B: TBitmap; Sig: String; Tw, Th: Integer;
begin
  Sig := IntToStr(State) + '|' + Cap;
  if Sig = Shown then Exit;
  Shown := Sig;
  B := ScaledBmp(UnBase[Kind * 4 + State], Img.Width, Img.Height);
  try
    B.Canvas.Font.Name := 'Segoe UI Semibold';
    B.Canvas.Font.Size := 10;
    B.Canvas.Brush.Style := bsClear;
    if State = 3 then B.Canvas.Font.Color := $82705A
    else if (Kind = 0) or (State > 0) then B.Canvas.Font.Color := clWhite
    else B.Canvas.Font.Color := $F0D8CC;
    Tw := B.Canvas.TextWidth(Cap);
    Th := B.Canvas.TextHeight(Cap);
    B.Canvas.TextOut((B.Width - Tw) div 2, (B.Height - Th) div 2 - 1, Cap);
    Img.Bitmap.Assign(B);
  finally
    B.Free;
  end;
end;

function UnLabel(Owner: TComponent; Parent: TWinControl; const Caption: String; Left, Top, Width, Size: Integer;
  Color: TColor; const FontName: String): TNewStaticText;
begin
  Result := TNewStaticText.Create(Owner);
  Result.Parent := Parent;
  Result.Left := Left;
  Result.Top := Top;
  Result.Width := Width;
  Result.AutoSize := True;
  Result.WordWrap := False;
  Result.Font.Name := FontName;
  Result.Font.Size := Size;
  Result.Font.Color := Color;
  Result.Caption := Caption;
end;

procedure UnPaintFill(W: Integer);
var B: TBitmap; H, Cap: Integer;
begin
  H := ScaleY(8);
  Cap := H div 2;
  B := TBitmap.Create;
  try
    B.Width := W;
    B.Height := H;
    SetStretchBltMode(B.Canvas.Handle, 4);
    StretchBlt(B.Canvas.Handle, 0, 0, Cap, H, UnFillL.Canvas.Handle, 0, 0, UnFillL.Width, UnFillL.Height, $CC0020);
    if W > Cap * 2 then
      StretchBlt(B.Canvas.Handle, Cap, 0, W - Cap * 2, H, UnFillM.Canvas.Handle, 0, 0, UnFillM.Width, UnFillM.Height, $CC0020);
    StretchBlt(B.Canvas.Handle, W - Cap, 0, Cap, H, UnFillR.Canvas.Handle, 0, 0, UnFillR.Width, UnFillR.Height, $CC0020);
    UpFill.Width := W;
    UpFill.Bitmap.Assign(B);
  finally
    B.Free;
  end;
end;

procedure UpRefreshSteps;
var I: Integer;
begin
  for I := 0 to 3 do begin
    if I < UpStage then begin
      UpG[I].Caption := #$2713; UpG[I].Font.Color := clGood;
      UpT[I].Font.Color := clMuted; UpT[I].Font.Style := [];
    end else if I = UpStage then begin
      UpG[I].Caption := #$2192; UpG[I].Font.Color := clAccent;
      UpT[I].Font.Color := clText; UpT[I].Font.Style := [fsBold];
    end else begin
      UpG[I].Caption := #$25CB; UpG[I].Font.Color := clDim;
      UpT[I].Font.Color := clDim; UpT[I].Font.Style := [];
    end;
  end;
end;

procedure UpSetStage(S: Integer; const Live: String);
begin
  if (UpStatus = nil) or (not UpFormAlive) then Exit;
  UpStage := S;
  UpLive.Caption := Live;
  UpRefreshSteps;
end;

// Progress comes from Inno's own uninstall progress bar (real removal progress).
procedure UpSyncProgress;
var Cur, Mx, Pct, W, St: Integer;
begin
  Mx := UninstallProgressForm.ProgressBar.Max;
  Cur := UninstallProgressForm.ProgressBar.Position;
  if (UpStage = 2) and (Mx > 0) and (Cur >= Mx) then begin
    // Inno's own removal pass has finished (progress bar full): what remains is finalizing.
    UpStage := 3;
    UpLive.Caption := 'Finalizing removal...';
    UpRefreshSteps;
  end;
  if UpStage >= 3 then Pct := 100
  else if (UpStage = 2) and (Mx > 0) then Pct := Integer((Int64(Cur) * 100) div Mx)
  else Pct := 0;
  W := (UpTrackW - ScaleX(6)) * Pct div 100;
  if W < ScaleX(8) then W := ScaleX(8);
  if W <> UpLastW then begin
    UpLastW := W;
    UnPaintFill(W);
    UpPct.Caption := IntToStr(Pct) + '%';
    UpPct.Left := UpTrack.Left + UpTrackW - UpPct.Width;
  end;
  UpFill.Visible := Pct > 0;
  if (UpStage = 2) and (UninstallProgressForm.StatusLabel.Caption <> '') then
    UpLive.Caption := UninstallProgressForm.StatusLabel.Caption;
  // custom Cancel mirrors Inno's (normally hidden/disabled during removal)
  UpCancelImg.Visible := UninstallProgressForm.CancelButton.Visible;
  if UpCancelImg.Visible then begin
    St := HoverState(UpCancelImg, UninstallProgressForm.CancelButton.Enabled);
    UnPaintBtn(UpCancelImg, 1, St, 'Cancel', UpCancelShown);
    if UnClickEdge(2, UpCancelImg) and UninstallProgressForm.CancelButton.Enabled then
      PostMessage(UninstallProgressForm.CancelButton.Handle, BM_CLICK, 0, 0);
  end;
end;

procedure UnTick(H: LongWord; Msg: LongWord; IdEvent: LongWord; Time: LongWord);
var I: Integer; Clicked: Boolean;
begin
  try
    if UnMode = 1 then begin
      for I := 0 to 1 do
        if UnDlgImg[I].Visible then begin
          Clicked := UnClickEdge(I, UnDlgImg[I]);
          UnPaintBtn(UnDlgImg[I], I, HoverState(UnDlgImg[I], True), UnDlgCap[I], UnDlgShown[I]);
          if Clicked then begin
            UnDlgOk := (I = 0);
            UnDlg.Close;
          end;
        end;
    end else if UnMode = 2 then
      UpSyncProgress;
  except
  end;
end;

// Full-window Motiva dialog: hero artwork + primary (and optional secondary) button.
// Returns True when the primary button was chosen.
function ShowUnDialog(Hero: TBitmap; const PrimaryCap, SecondaryCap, StatusTxt: String): Boolean;
var Img: TBitmapImage; HeroH, X, I: Integer; L: TNewStaticText; HB: TBitmap;
begin
  UnDlg := CreateCustomForm(ScaleX(600), ScaleY(460), False, False);
  try
    // CreateCustomForm scales its size again; set the real pixel size explicitly so the
    // window matches the installer's.
    UnDlg.ClientWidth := ScaleX(600);
    UnDlg.ClientHeight := ScaleY(460);
    UnDlg.Caption := 'Motiva Uninstall';
    UnDlg.Color := clBg;
    UnDlg.Font.Name := 'Segoe UI';
    HeroH := UnDlg.ClientHeight - ScaleY(72);
    Img := TBitmapImage.Create(UnDlg);
    Img.Parent := UnDlg;
    Img.SetBounds(0, 0, UnDlg.ClientWidth, HeroH);
    HB := ScaledBmp(Hero, UnDlg.ClientWidth, HeroH);
    Img.Bitmap.Assign(HB);
    HB.Free;

    X := UnDlg.ClientWidth - ScaleX(24);
    for I := 0 to 1 do begin
      UnDlgImg[I] := TBitmapImage.Create(UnDlg);
      UnDlgImg[I].Parent := UnDlg;
      UnDlgImg[I].Stretch := False;
      UnDlgImg[I].Cursor := crHand;
      if I = 0 then UnDlgImg[I].Width := ScaleX(150) else UnDlgImg[I].Width := ScaleX(110);
      UnDlgImg[I].Height := ScaleY(40);
      UnDlgImg[I].Top := UnDlg.ClientHeight - ScaleY(58);
      UnDlgShown[I] := '';
      UnPrev[I] := False;
    end;
    UnDlgCap[0] := PrimaryCap;
    UnDlgCap[1] := SecondaryCap;
    UnDlgImg[0].Left := X - UnDlgImg[0].Width;
    UnDlgImg[1].Left := UnDlgImg[0].Left - ScaleX(10) - UnDlgImg[1].Width;
    UnDlgImg[1].Visible := SecondaryCap <> '';

    L := UnLabel(UnDlg, UnDlg, #$25CF + '  Motiva  ' + #$2022 + '  ' + StatusTxt, ScaleX(28),
      UnDlg.ClientHeight - ScaleY(48), ScaleX(300), 9, clDim, 'Segoe UI');
    UnPaintBtn(UnDlgImg[0], 0, 0, UnDlgCap[0], UnDlgShown[0]);
    if SecondaryCap <> '' then UnPaintBtn(UnDlgImg[1], 1, 0, UnDlgCap[1], UnDlgShown[1]);

    UnMode := 1;
    UnTimerId := SetTimer(0, 0, 30, CreateCallback(@UnTick));
    UnDlgOk := False;
    UnDlg.ShowModal;
    Result := UnDlgOk;
  finally
    UnMode := 0;
    if UnTimerId <> 0 then KillTimer(0, UnTimerId);
    UnTimerId := 0;
    UnDlg.Free;
  end;
end;

function InitializeUninstall: Boolean;
var R: Integer;
begin
  Result := True;
  // Silent runs and any failure to load the Motiva UI fall through to Inno's own flow.
  if HasParam('/VERYSILENT') or UninstallSilent then Exit;
  UnLoadAssets;
  if not UnAssetsReady then Exit;
  if not ShowUnDialog(UnHeroWelcome, 'Uninstall', 'Cancel', 'Uninstall') then begin
    Result := False; // user cancelled
    Exit;
  end;
  // Relaunch silently (no native confirm / finish boxes) with the Motiva UI switch.
  if Exec(ExpandConstant('{uninstallexe}'), '/SILENT /MOTIVAUI', '', SW_SHOWNORMAL, ewNoWait, R) then
    Result := False;
end;

procedure InitializeUninstallProgressForm;
var F: TUninstallProgressForm; Pg: TNewNotebookPage; PW, I, Y, TX: Integer; T: TNewStaticText;
  Names: array[0..3] of String; Tmp: TBitmap;
begin
  if HasParam('/VERYSILENT') then Exit;
  UnLoadAssets;
  if not UnAssetsReady then Exit;
  F := UninstallProgressForm;
  F.Font.Name := 'Segoe UI';
  F.ClientWidth := ScaleX(600);
  F.ClientHeight := ScaleY(460);
  F.Color := clBg;
  F.MainPanel.Visible := False;
  F.Bevel.Visible := False;
  F.Bevel1.Visible := False;
  F.BeveledLabel.Visible := False;
  F.OuterNotebook.Height := F.ClientHeight - F.OuterNotebook.Top - ScaleY(72);
  F.InnerPage.Color := clBg;
  F.InstallingPage.Color := clBg;
  F.InnerNotebook.Top := 0;
  F.InnerNotebook.Height := F.InnerPage.Height;
  F.StatusLabel.Visible := False;
  F.ProgressBar.Visible := False;

  Pg := F.InstallingPage;
  PW := Pg.Width;
  T := UnLabel(F, Pg, 'Uninstalling Motiva', 0, ScaleY(34), PW, 24, clText, 'Segoe UI Light');
  T.Left := (PW - T.Width) div 2;
  T := UnLabel(F, Pg, 'Removing Motiva from this computer.', 0, ScaleY(80), PW, 11, clMuted, 'Segoe UI');
  T.Left := (PW - T.Width) div 2;

  UpTrackW := (PW * 90) div 100;
  TX := (PW - UpTrackW) div 2;
  Y := ScaleY(130);
  UpTrack := TBitmapImage.Create(F);
  UpTrack.Parent := Pg;
  UpTrack.SetBounds(TX, Y, UpTrackW, ScaleY(14));
  Tmp := TBitmap.Create;
  Tmp.LoadFromFile(UnAsset('progress-track.bmp'));
  UpTrack.Bitmap.Assign(ScaledBmp(Tmp, UpTrackW, ScaleY(14)));
  Tmp.Free;
  UpFill := TBitmapImage.Create(F);
  UpFill.Parent := Pg;
  UpFill.SetBounds(TX + ScaleX(3), Y + ScaleY(3), ScaleX(8), ScaleY(8));
  UpLastW := -1;
  UnPaintFill(ScaleX(8));
  UpFill.Visible := False;
  UpPct := UnLabel(F, Pg, '0%', TX, Y - ScaleY(26), ScaleX(60), 10, clAccent, 'Segoe UI');
  UpPct.Font.Style := [fsBold];
  UpPct.Left := TX + UpTrackW - UpPct.Width;

  Names[0] := 'Preparing to uninstall';
  Names[1] := 'Removing Explorer integration';
  Names[2] := 'Removing application files and Start Menu shortcut';
  Names[3] := 'Finalizing removal';
  Y := ScaleY(172);
  for I := 0 to 3 do begin
    UpG[I] := UnLabel(F, Pg, #$25CB, TX + ScaleX(6), Y, ScaleX(24), 11, clDim, 'Segoe UI Symbol');
    UpT[I] := UnLabel(F, Pg, Names[I], TX + ScaleX(38), Y + ScaleY(1), UpTrackW - ScaleX(44), 11, clDim, 'Segoe UI');
    Y := Y + ScaleY(26);
  end;
  UpLive := UnLabel(F, Pg, 'Preparing to uninstall...', TX, Y + ScaleY(10), UpTrackW, 10, clMuted, 'Segoe UI');

  UpStatus := UnLabel(F, F, #$25CF + '  Motiva  ' + #$2022 + '  Uninstalling Motiva  ' + #$2022 + '  Please wait...',
    ScaleX(28), F.ClientHeight - ScaleY(48), ScaleX(300), 9, clDim, 'Segoe UI');

  // custom Cancel (Inno's own is parked off-screen; its state is mirrored)
  UpCancelImg := TBitmapImage.Create(F);
  UpCancelImg.Parent := F;
  UpCancelImg.Stretch := False;
  UpCancelImg.Cursor := crHand;
  UpCancelImg.Width := ScaleX(110);
  UpCancelImg.Height := ScaleY(40);
  UpCancelImg.Left := F.ClientWidth - ScaleX(24) - UpCancelImg.Width;
  UpCancelImg.Top := F.ClientHeight - ScaleY(58);
  UpCancelShown := '';
  F.CancelButton.Left := -3000;

  UpStage := 0;
  UpRefreshSteps;
  UpFormAlive := True;
  UnMode := 2;
  UnTimerId := SetTimer(0, 0, 30, CreateCallback(@UnTick));
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
  // What gets removed is unchanged: stop a running Motiva, remove Motiva's own
  // Explorer verb + autostart value, then Inno removes files/shortcut/registry entries.
  if CurUninstallStep = usUninstall then begin
    UpSetStage(0, 'Preparing to uninstall...');
    StopMotiva;
    UpSetStage(1, 'Removing Explorer integration...');
    CleanMotivaShellRegistration;
    UpSetStage(2, 'Removing application files and Start Menu shortcut...');
  end else if CurUninstallStep = usPostUninstall then begin
    // The progress form no longer exists from here on: stop the timer, never touch it again.
    UpFormAlive := False;
    UnMode := 0;
    if UnTimerId <> 0 then KillTimer(0, UnTimerId);
    UnTimerId := 0;
  end else if CurUninstallStep = usDone then begin
    UpFormAlive := False;
    UnMode := 0;
    if UnTimerId <> 0 then KillTimer(0, UnTimerId);
    UnTimerId := 0;
    if UnAssetsReady and HasParam('/MOTIVAUI') and (not HasParam('/VERYSILENT')) then begin
      ShowUnDialog(UnHeroDone, 'Done', '', 'Uninstall complete');
    end;
  end;
end;
