; Motiva installer. Build with installer\build-installer.ps1 (Release build ->
; `deploy` target -> clean staging -> this script -> release\MotivaSetup.exe).
; Visual design: dark aurora theme implemented with native Inno Setup features
; only (custom pages, recoloured wizard surfaces, hero artwork from
; installer\assets, generated by installer\make-art.ps1).
#define AppName "Motiva"
#define AppVersion "1.0.0"
#define AppPublisher "Robin Gupta Studios"
#define StagingDir "..\release\staging"

[Setup]
AppId={{6D0F3B52-7A1E-4C1B-9B0B-4D0E5A6F2C91}
AppName={#AppName}
AppVersion={#AppVersion}
AppVerName={#AppName} {#AppVersion}
AppPublisher={#AppPublisher}
AppCopyright=Copyright © Robin Gupta
VersionInfoVersion=1.0.0.0
VersionInfoCompany={#AppPublisher}
VersionInfoCopyright=Copyright © Robin Gupta
VersionInfoProductName={#AppName}
VersionInfoDescription={#AppName} Setup
; Per-user install: Motiva only writes to HKCU / per-user Start Menu, so no
; administrator rights (and no "install for all users?" prompt) are needed.
PrivilegesRequired=lowest
DefaultDirName={autopf}\{#AppName}
DisableProgramGroupPage=yes
; Welcome, power notice and options are custom-styled pages (see [Code]).
DisableWelcomePage=no
DisableDirPage=yes
DisableReadyPage=yes
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
OutputDir=..\release
OutputBaseFilename=MotivaSetup
SetupIconFile=assets\motiva.ico
UninstallDisplayIcon={app}\resources\bin\Motiva.exe
UninstallDisplayName={#AppName}
WizardStyle=modern
WizardImageFile=assets\motiva-installer-welcome.png
WizardSmallImageFile=assets\motiva-installer-banner.png
Compression=lzma2/max
SolidCompression=yes
CloseApplications=force
; No LicenseFile: the repository has no license file, and none is invented.

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Messages]
StatusExtractFiles=Installing application
SetupWindowTitle=Motiva Setup
FinishedHeadingLabel=Motiva is ready
FinishedLabelNoIcons=Your desktop is ready for motion.
FinishedLabel=Your desktop is ready for motion.

[Files]
Source: "{#StagingDir}\*"; DestDir: "{app}"; Flags: recursesubdirs createallsubdirs ignoreversion
Source: "assets\motiva-installer-finish.bmp"; DestDir: "{tmp}"; Flags: dontcopy

[Icons]
; Target is the deployed launcher; the icon comes from the real binary.
Name: "{autoprograms}\{#AppName}"; Filename: "{app}\Motiva.exe"; WorkingDir: "{app}"; IconFilename: "{app}\resources\bin\Motiva.exe"; Check: WantStartMenuShortcut
Name: "{autodesktop}\{#AppName}"; Filename: "{app}\Motiva.exe"; WorkingDir: "{app}"; IconFilename: "{app}\resources\bin\Motiva.exe"; Check: WantDesktopShortcut

[Run]
Filename: "{app}\Motiva.exe"; Description: "Launch Motiva"; Flags: nowait postinstall skipifsilent

[Code]
const
  // Colours are BGR. Palette: deep midnight background, slightly lifted
  // panels, soft lavender body text, cyan accent.
  clBg      = $1E0E0C;
  clPanel   = $2C1815;
  clText    = $FFFFFF;
  clMuted   = $E6C9BC;
  clAccent  = $FFC25A;

var
  PowerPage, OptionsPage: TWizardPage;
  PowerCheck: TNewCheckBox;
  DirEditBox: TNewEdit;
  StartMenuCheck, DesktopCheck: TNewCheckBox;
  PowerLbl, StartLbl, DesktopLbl: TNewStaticText;

function WantStartMenuShortcut: Boolean;
begin
  // Silent installs (custom pages never shown) keep the default: Start Menu on.
  if StartMenuCheck = nil then Result := True else Result := StartMenuCheck.Checked;
end;

function WantDesktopShortcut: Boolean;
begin
  if DesktopCheck = nil then Result := False else Result := DesktopCheck.Checked;
end;

procedure ThemeControls(Parent: TWinControl);
var I: Integer; C: TControl;
begin
  for I := 0 to Parent.ControlCount - 1 do begin
    C := Parent.Controls[I];
    if C is TNewStaticText then TNewStaticText(C).Font.Color := clMuted
    else if C is TNewCheckBox then TNewCheckBox(C).Font.Color := clText
    else if C is TNewCheckListBox then begin
      TNewCheckListBox(C).Color := clBg;
      TNewCheckListBox(C).Font.Color := clText;
    end;
    if C is TWinControl then ThemeControls(TWinControl(C));
  end;
end;

procedure UpdatePowerNext;
begin
  if WizardForm.CurPageID = PowerPage.ID then
    WizardForm.NextButton.Enabled := PowerCheck.Checked or WizardSilent;
end;

procedure PowerCheckClick(Sender: TObject);
begin
  UpdatePowerNext;
end;

procedure BrowseClick(Sender: TObject);
var S: String;
begin
  S := DirEditBox.Text;
  if BrowseForFolder('Choose where to install Motiva', S, True) then
    DirEditBox.Text := S;
end;

function AddLabel(Page: TWizardPage; const Caption: String; Top, Size: Integer; Bold: Boolean; Color: TColor): TNewStaticText;
begin
  Result := TNewStaticText.Create(Page);
  Result.Parent := Page.Surface;
  Result.Left := 0;
  Result.Top := Top;
  Result.Width := Page.SurfaceWidth;
  Result.AutoSize := True;
  Result.WordWrap := True;
  Result.Caption := Caption;
  Result.Font.Name := 'Segoe UI';
  Result.Font.Size := Size;
  if Bold then Result.Font.Style := [fsBold];
  Result.Font.Color := Color;
end;

// Native checkboxes ignore Font.Color for their caption (black text on the
// dark surface), so each option is a checkbox with an empty caption plus a
// light, clickable label beside it.
function AddCheck(Page: TWizardPage; const Caption: String; Top, Height: Integer; Checked: Boolean; Lbl: TNewStaticText): TNewCheckBox;
begin
  Result := TNewCheckBox.Create(Page);
  Result.Parent := Page.Surface;
  Result.Left := 0;
  Result.Top := Top;
  Result.Width := ScaleX(20);
  Result.Height := ScaleY(20);
  Result.Caption := '';
  Result.Checked := Checked;
  Lbl.Parent := Page.Surface;
  Lbl.Left := ScaleX(26);
  Lbl.Top := Top + ScaleY(1);
  Lbl.Width := Page.SurfaceWidth - ScaleX(26);
  Lbl.AutoSize := True;
  Lbl.WordWrap := True;
  Lbl.Caption := Caption;
  Lbl.Font.Name := 'Segoe UI';
  Lbl.Font.Size := 10;
  Lbl.Font.Color := clText;
  Lbl.Cursor := crHand;
end;

procedure PowerLabelClick(Sender: TObject);
begin
  PowerCheck.Checked := not PowerCheck.Checked;
end;

procedure StartLabelClick(Sender: TObject);
begin
  StartMenuCheck.Checked := not StartMenuCheck.Checked;
end;

procedure DesktopLabelClick(Sender: TObject);
begin
  DesktopCheck.Checked := not DesktopCheck.Checked;
end;

procedure BuildPowerPage;
var Head, Body, Body2, Body3: TNewStaticText; Y: Integer;
begin
  PowerPage := CreateCustomPage(wpWelcome, 'Important Power Usage Notice',
    'Please review this before installing Motiva.');
  Head := AddLabel(PowerPage, 'Power && Battery Usage', 0, 13, True, clAccent);
  Y := Head.Top + Head.Height + ScaleY(10);
  Body := AddLabel(PowerPage,
    'Motiva uses video and animated content to display motion on your desktop. Depending on the selected media, ' +
    'resolution, frame rate, hardware, and system configuration, animated wallpapers may consume significantly more ' +
    'CPU/GPU power than a traditional static wallpaper.', Y, 10, False, clMuted);
  Y := Body.Top + Body.Height + ScaleY(10);
  Body2 := AddLabel(PowerPage,
    'When running on battery power, this can result in higher battery usage and reduced battery runtime.', Y, 10, False, clMuted);
  Y := Body2.Top + Body2.Height + ScaleY(10);
  Body3 := AddLabel(PowerPage,
    'Motiva provides settings that allow you to control whether video wallpaper remains active while your device is ' +
    'running on battery. Please review these settings after installation if battery life is important to you.',
    Y, 10, False, clMuted);
  Y := Body3.Top + Body3.Height + ScaleY(18);

  PowerLbl := TNewStaticText.Create(PowerPage);
  PowerLbl.OnClick := @PowerLabelClick;
  PowerCheck := AddCheck(PowerPage,
    'I understand that animated/video wallpapers may consume more power and may result in higher battery usage.',
    Y, 40, False, PowerLbl);
  PowerCheck.OnClick := @PowerCheckClick;
end;

procedure BuildOptionsPage;
var L1, L2: TNewStaticText; Browse: TNewButton; Y: Integer;
begin
  OptionsPage := CreateCustomPage(PowerPage.ID, 'Installation Options',
    'Choose where Motiva is installed and which shortcuts to create.');
  L1 := AddLabel(OptionsPage, 'Install location', 0, 11, True, clAccent);
  Y := L1.Top + L1.Height + ScaleY(8);

  DirEditBox := TNewEdit.Create(OptionsPage);
  DirEditBox.Parent := OptionsPage.Surface;
  DirEditBox.Left := 0;
  DirEditBox.Top := Y;
  DirEditBox.Width := OptionsPage.SurfaceWidth - ScaleX(110);
  DirEditBox.Font.Name := 'Segoe UI';
  DirEditBox.Font.Size := 10;
  DirEditBox.Text := WizardForm.DirEdit.Text;

  Browse := TNewButton.Create(OptionsPage);
  Browse.Parent := OptionsPage.Surface;
  Browse.Left := DirEditBox.Width + ScaleX(10);
  Browse.Top := Y - ScaleY(1);
  Browse.Width := ScaleX(100);
  Browse.Height := DirEditBox.Height + ScaleY(2);
  Browse.Caption := 'Browse...';
  Browse.OnClick := @BrowseClick;

  Y := DirEditBox.Top + DirEditBox.Height + ScaleY(28);
  L2 := AddLabel(OptionsPage, 'Shortcuts', Y, 11, True, clAccent);
  Y := L2.Top + L2.Height + ScaleY(10);

  StartLbl := TNewStaticText.Create(OptionsPage);
  StartLbl.OnClick := @StartLabelClick;
  StartMenuCheck := AddCheck(OptionsPage, 'Start Menu shortcut', Y, 20, True, StartLbl);
  DesktopLbl := TNewStaticText.Create(OptionsPage);
  DesktopLbl.OnClick := @DesktopLabelClick;
  DesktopCheck := AddCheck(OptionsPage, 'Desktop shortcut', Y + ScaleY(34), 20, False, DesktopLbl);
end;

procedure InitializeWizard;
var FinishImg: String; HeroH: Integer;
begin
  WizardForm.Font.Name := 'Segoe UI';
  WizardForm.Color := clBg;
  WizardForm.MainPanel.Color := clPanel;
  WizardForm.InnerPage.Color := clBg;
  WizardForm.WelcomePage.Color := clBg;
  WizardForm.FinishedPage.Color := clBg;

  // Full-bleed hero on the welcome page: the artwork carries the wordmark,
  // tagline and description, so the stock labels are hidden.
  WizardForm.WizardBitmapImage.Left := 0;
  WizardForm.WizardBitmapImage.Top := 0;
  WizardForm.WizardBitmapImage.Width := WizardForm.WelcomePage.Width;
  WizardForm.WizardBitmapImage.Height := WizardForm.WelcomePage.Height;
  WizardForm.WizardBitmapImage.Stretch := True;
  WizardForm.WelcomeLabel1.Visible := False;
  WizardForm.WelcomeLabel2.Visible := False;
  Log('WelcomePage=' + IntToStr(WizardForm.WelcomePage.Width) + 'x' + IntToStr(WizardForm.WelcomePage.Height) +
      ' Inner=' + IntToStr(WizardForm.InnerPage.Width) + 'x' + IntToStr(WizardForm.InnerPage.Height));

  // Finish page: separate hero, launch checkbox (RunList) sits beneath it.
  ExtractTemporaryFile('motiva-installer-finish.bmp');
  FinishImg := ExpandConstant('{tmp}\motiva-installer-finish.bmp');
  WizardForm.WizardBitmapImage2.Bitmap.LoadFromFile(FinishImg);
  WizardForm.WizardBitmapImage2.Left := 0;
  WizardForm.WizardBitmapImage2.Top := 0;
  WizardForm.WizardBitmapImage2.Width := WizardForm.FinishedPage.Width;
  HeroH := (WizardForm.FinishedPage.Width * 2) div 5;
  WizardForm.WizardBitmapImage2.Height := HeroH;
  WizardForm.WizardBitmapImage2.Stretch := True;
  WizardForm.FinishedHeadingLabel.Visible := False;
  WizardForm.FinishedLabel.Visible := False;
  WizardForm.RunList.Left := (WizardForm.FinishedPage.Width - ScaleX(220)) div 2;
  WizardForm.RunList.Top := HeroH + ScaleY(28);
  WizardForm.RunList.Width := ScaleX(220);
  WizardForm.RunList.Height := ScaleY(60);

  ThemeControls(WizardForm);
  WizardForm.PageNameLabel.Font.Color := clText;
  BuildPowerPage;
  BuildOptionsPage;
end;

procedure CurPageChanged(CurPageID: Integer);
begin
  WizardForm.NextButton.Caption := SetupMessage(msgButtonNext);
  case CurPageID of
    wpWelcome: WizardForm.NextButton.Caption := 'Get Started  ' + #$2192;
    wpInstalling: begin
      WizardForm.PageNameLabel.Caption := 'Installing Motiva';
      WizardForm.PageDescriptionLabel.Caption := 'Preparing your desktop experience...';
    end;
    wpFinished: begin
      WizardForm.NextButton.Caption := SetupMessage(msgButtonFinish);
      // Inno repositions the run list when this page opens, so place it here.
      WizardForm.RunList.Top := WizardForm.WizardBitmapImage2.Height + ScaleY(28);
      WizardForm.RunList.Left := (WizardForm.FinishedPage.Width - WizardForm.RunList.Width) div 2;
    end;
  end;
  if CurPageID = PowerPage.ID then begin
    WizardForm.NextButton.Caption := 'Continue  ' + #$2192;
    UpdatePowerNext;
  end;
  if CurPageID = OptionsPage.ID then
    WizardForm.NextButton.Caption := 'Install  ' + #$2192;
end;

function NextButtonClick(CurPageID: Integer): Boolean;
begin
  Result := True;
  if CurPageID = PowerPage.ID then begin
    // Interactive acknowledgement gate (the button is also disabled until ticked).
    // Unattended /SILENT installs have no one to ask, so they pass through.
    Result := PowerCheck.Checked or WizardSilent;
    if not Result then MsgBox('Please confirm that you understand the power usage notice to continue.', mbInformation, MB_OK);
  end
  else if CurPageID = OptionsPage.ID then begin
    if Trim(DirEditBox.Text) = '' then begin
      MsgBox('Please choose an installation folder.', mbError, MB_OK);
      Result := False;
    end else
      WizardForm.DirEdit.Text := DirEditBox.Text;
  end;
end;

function StopMotiva: Integer;
var R: Integer;
begin
  Exec(ExpandConstant('{sys}\taskkill.exe'), '/F /IM Motiva.exe', '', SW_HIDE, ewWaitUntilTerminated, R);
  Result := R;
end;

function PrepareToInstall(var NeedsRestart: Boolean): String;
begin
  StopMotiva;
  Result := '';
end;

// Removes ONLY Motiva's own Explorer verb (MotivaSetBackground) under each
// per-user SystemFileAssociations extension, and its autostart value.
// User settings (HKCU\Software\Motiva), recovery state and media are kept.
procedure CleanMotivaShellRegistration;
var Names: TArrayOfString; I: Integer; Base: String;
begin
  Base := 'Software\Classes\SystemFileAssociations';
  if RegGetSubkeyNames(HKCU, Base, Names) then
    for I := 0 to GetArrayLength(Names) - 1 do
      if RegKeyExists(HKCU, Base + '\' + Names[I] + '\shell\MotivaSetBackground') then
        RegDeleteKeyIncludingSubkeys(HKCU, Base + '\' + Names[I] + '\shell\MotivaSetBackground');
  RegDeleteValue(HKCU, 'Software\Microsoft\Windows\CurrentVersion\Run', 'Motiva');
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
  if CurUninstallStep = usUninstall then begin
    StopMotiva;
    CleanMotivaShellRegistration;
  end;
end;
